config/routes.rb
Rails.application.routes.draw do

  root 'admins/transactions#index'

  scope module: 'admins', path: 'admins' do
    resources :merchants, except: :new
    resources :transactions, only: %i[show index]
    resources :authorize_transactions, only: %i[show index], controller: 'transactions'
    resources :charge_transactions, only: %i[show index], controller: 'transactions'
  end

  namespace :api do
    namespace :v1 do
      namespace :merchants do
        post ':merchant_id/transactions', to: 'transactions#create'
      end
    end
  end

  devise_for :admins
  devise_for :merchants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/admins/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    a.navbar-brand href="#"  Emerchant Test Project
    button.navbar-toggler aria-controls="navbarScroll" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarScroll" data-bs-toggle="collapse" type="button"
      span.navbar-toggler-icon
    #navbarScroll.collapse.navbar-collapse
      ul.navbar-nav.ms-auto.my-2.my-lg-0.navbar-nav-scroll style=("--bs-scroll-height: 100px")
        li.nav-item
          = link_to "Transactions", transactions_path, class: "#{current_page?(transactions_path) ? 'nav-link active' : 'nav-link'}"
        li.nav-item
          = link_to "Merchants", merchants_path, class: "#{current_page?(merchants_path) ? 'nav-link active' : 'nav-link'}"
        li.nav-item
          = link_to "Sign Out", destroy_admin_session_path, class: 'nav-link active', data: { turbo_method: :delete }