config/routes.rb
Rails.application.routes.draw do

  root 'admins/transactions#index'

  scope module: 'admins', path: 'admins' do
    resources :merchants, except: :new
    resources :transactions, only: %i[show index]
    resources :authorize_transactions, only: %i[show index], controller: 'transactions'
    resources :charge_transactions, only: %i[show index], controller: 'transactions'
  end

  namespace :api do
    namespace :v1 do
      namespace :merchants do
        post ':merchant_id/transactions', to: 'transactions#create'
      end
    end
  end

  devise_for :admins
  devise_for :merchants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/merchant.rb
# frozen_string_literal: true

class Merchant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :email, :name, :status
  validates_uniqueness_of :email
  validates_inclusion_of :status, in: %w[active inactive]
  has_many :transactions, dependent: :restrict_with_error
  has_many :authorize_transactions, dependent: :restrict_with_error
  has_many :charge_transactions, dependent: :restrict_with_error
  has_many :refund_transactions, dependent: :restrict_with_error
  has_many :reversal_transactions, dependent: :restrict_with_error
  before_destroy :check_for_active_transactions
  after_create :generate_api_credentials

  def check_for_active_transactions
    if transactions.count.positive?
      errors.add_to_base('Cannot delete merchant while transaction exist')
      false
    end
  end

  def total_transaction_sum
    charge_transactions.where(status: 'approved').sum(:amount).to_i
  end

  def generate_api_credentials
    update(api_user_name: "#{name}%.5d" % SecureRandom.random_number(99))
    update(api_password: SecureRandom.random_number(9999))
  end

  def authenticate(user_name, password)
    api_user_name == user_name && api_password == password && status == 'active' ? self : false
  end
end

app/controllers/admins/merchants_controller.rb
# frozen_string_literal: true

module Admins
  class MerchantsController < ApplicationController
    before_action :set_merchant, only: %i[show edit update destroy]

    # GET /admins/merchants or /admins/merchants.json
    def index
      @merchants = Merchant.all
    end

    # GET /admins/merchants/1 or /admins/merchants/1.json
    def show; end

    # GET /admins/merchants/new
    def new
      @merchant = Merchant.new
    end

    # GET /admins/merchants/1/edit
    def edit; end

    # PATCH/PUT /admins/merchants/1 or /admins/merchants/1.json
    def update
      respond_to do |format|
        if @merchant.update(merchant_params)
          format.html { redirect_to merchant_url(@merchant), notice: 'Merchant was successfully updated.' }
          format.json { render :show, status: :ok, location: @merchant }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @merchant.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admins/merchants/1 or /admins/merchants/1.json
    def destroy
      @merchant.destroy

      respond_to do |format|
        format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def merchant_params
      params.require(:merchant).permit(:name, :status, :description)
    end
  end
end

app/controllers/api/v1/merchants/transactions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Merchants
      class TransactionsController < ApplicationController
        protect_from_forgery unless: -> { request.format.json? }
        before_action :set_merchant, :authenticate

        def create
          @transaction = @current_merchant.transactions.new(transaction_params)
          if @transaction.save
            render json: @transaction
          else
            render json: { message: @transaction.errors }
          end
        end

        private

        def authenticate
          if user = authenticate_with_http_basic { |u, p| @merchant.authenticate(u, p) }
            @current_merchant = user
          else
            request_http_basic_authentication
          end
        end

        def set_merchant
          @merchant = Merchant.find(params[:merchant_id])
        end

        def transaction_params
          params.require(:transaction).permit(:amount, :customer_email, :customer_phone, :status, :type,
                                              :authorize_transaction_id, :charge_transaction_id)
        end
      end
    end
  end
end

app/controllers/merchants/transactions_controller.rb
class Merchants::TransactionsController < ApplicationController
  before_action :authenticate_merchant!

  # GET /merchants/transactions or /merchants/transactions.json
  layout 'merchant'
  def index
    @transactions = current_merchant.transactions.all
  end
end

app/helpers/admins/merchants_helper.rb
# frozen_string_literal: true

module Admins
  module MerchantsHelper
  end
end

app/helpers/merchants/transactions_helper.rb
module Merchants::TransactionsHelper
end

app/views/admins/merchants/_form.html.slim
= form_with model: @merchant do |f|
  - if @merchant.errors.any?
    #error_explanation
      h2 = "#{pluralize(@merchant.errors.count, 'error')} prohibited this admins_merchant from being saved:"
      ul
        - @merchant.errors.full_messages.each do |message|
          li = message

  div.field
    = f.label :name
    br
    = f.text_field :name
  div.field
    = f.label :description
    br
    = f.text_area :description
  div.field
    = f.label :status
    br
    = f.select :status, [['Active', 'active'], ['Inactive', 'inactive']]
  div.actions
      = f.submit

app/views/admins/merchants/destroy.html.slim
h1 Admins::Merchants#destroy
p Find me in app/views/admins/merchants/destroy.html.slim

app/views/admins/merchants/edit.html.slim
h1 Editing Merchant

== render 'form'

=< link_to 'Back', merchants_path

app/views/admins/merchants/index.html.slim
h1.text-center.mt-5 Merchants

.container.my-5
  table.table.caption-top
    thead
      tr
        th scope="col"  Sr#
        th scope="col"  Name
        th scope="col"  Email
        th scope="col"  Description
        th scope="col"  Status
        th scope="col"  Actions
    tbody
      - @merchants.each do |admins_merchant|
        tr
          th scope="row"  = admins_merchant.id
          td = admins_merchant.name
          td = admins_merchant.email
          td = admins_merchant.description
          td = admins_merchant.status
          td.d-flex.justify-content-around
            = link_to "Edit", edit_merchant_path(admins_merchant), class: "btn btn-primary text-white"
            = link_to "Show", merchant_path(admins_merchant), class: "btn btn-success text-white"
            - if admins_merchant.transactions.empty?
              = link_to "Delete", merchant_path(admins_merchant), class: "btn btn-danger text-white", data: { turbo_method: :delete }

app/views/admins/merchants/show.html.slim
h1.mt-5.text-center Merchant Details

.container.my-5
  table.table.caption-top
    tr
      td Merchant ID
      td = @merchant.id
    tr
      td Name
      td = @merchant.name
    tr
      td Email
      td = @merchant.email
    tr
      td Status
      td = @merchant.status

h1.text-center.mt-5 Transactions

.container.my-5
  table.table.caption-top
    thead
      tr
        th scope="col"  ID
        th scope="col"  Amount
        th scope="col"  Customer Email
        th scope="col"  Customer Phone
        th scope="col"  Status
        th scope="col"  Merchant ID
        th scope="col"  Type
        th
    tbody
      - @merchant.transactions.each do |merchant_transaction|
        tr
          th scope="row"  = merchant_transaction.id
          td = merchant_transaction.amount
          td = merchant_transaction.customer_email
          td = merchant_transaction.customer_phone
          td = merchant_transaction.status
          td = merchant_transaction.merchant_id
          td = merchant_transaction.type
          td.d-flex.justify-content-around
            = link_to "Show", transaction_path(merchant_transaction), class: "btn btn-success text-white"

  = link_to 'Back', merchants_path, class: "btn btn-success text-white"
  

app/views/admins/merchants/update.html.slim
h1 Admins::Merchants#update
p Find me in app/views/admins/merchants/update.html.slim